on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-actions@v1
      with:
        username: ${{ ganeskrish }}
        password: ${{ G9010268952@ }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
      push: true
      tags: ganeshkrish/maven-web-applicatio:latest, ganeshkrish/maven-web-application:${{github run number }}
